spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123123

mybatis-plus:
  configuration:
    #是否开启自动驼峰命名规则（camel case）映射，
    #即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射。
    #默认值：true
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: invalid  #全局逻辑删除字段值 3.3.0开始支持
      #逻辑已删除值,(逻辑删除下有效)
      logic-delete-value: 1
      #逻辑未删除值,(逻辑删除下有效)
      logic-not-delete-value: 0
      #字段验证策略
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL
      select-strategy: NOT_NULL
      #表名前缀
      table-prefix: t_
  mapper-locations: classpath*:mapper/*.xml
  #MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，
  #注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名
  #(即 XML 中调用的时候不用包含包名)
  type-aliases-package: com.flash.entity

logging:
  level:
    root: info
    com.flash.mapper: trace
  pattern: '%p%m%n'
